version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000/api}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:5228/api}
    command: npm run dev
    profiles:
      - dev
